name: 'Automation to kick off certain tests in certain clouds for a PR'
description: 'Get the label'
inputs:
  labels:
    description: 'Get function parameter'
    required: true
runs:
  using: 'docker'
  image: 'images/Dockerfile'
  args:
    - ${{ inputs.labels }}
