name: 'Automation to kick off certain tests in certain clouds for a PR'
description: 'Get the label'
inputs:
  function-name:
    description: 'Get function parameter'
    required: true
  cloud-name:
    description: 'Get cloud parameter'
    required: true
run: |
     chmod +x ./build.sh
     ./build.sh ${{ inputs.function-name }} ${{ inputs.cloud-name }}
