name: 'Hello World'
description: 'Get the tag'
inputs:
  tag-name:  # id of input
    description: 'Get tag parameter'
    required: true
    default: 'TAG'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tag-name }}
